spring:
  application:
    name: ms-discovery
server:
  port: ${SERVER_PORT:8761}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    


